### ISSUE TITLE
很好的lua，但有没有可能不用引导符就能完成？

### ISSUE THREAD

**Issue by sullevy** [HowcanoeWang/rime-lua-aux-code#12]
虽然现在这个方案已经比以前定制码表的方式好很多了，但不知道有没有可能，不用引导符直接支持辅助码运算的

**Comment by HowcanoeWang** [comment]
这样完全无法判断你输入的一串字符，哪些是拼音，哪些是辅助码，如果你是有单字输入的习惯，即三键或四键输入一个字，请直接用单字码表
