### ISSUE TITLE
另外建议：可以在雾凇拼音的基础上，整合一个版本发布

### ISSUE THREAD

**Issue by sullevy** [HowcanoeWang/rime-lua-aux-code#13]
不知道是我自己整合的问题，还是哪里有一点冲突
发现修改完雾凇拼音当中的方案，整合程度不高，转换的时候会有错误

全拼、双拼 都一样的问题

![image](https://github.com/HowcanoeWang/rime-lua-aux-code/assets/25456283/88979599-c0b8-4a41-9255-2aa39e776715)

**Comment by HowcanoeWang** [comment]
能不能提供一个动态的视频或者gif动图，单从这个截图上面无法判断原因
