### ISSUE TITLE
请问有没有什么方式取消显示辅码提示码

### ISSUE THREAD

**Issue by Ipseamor** [HowcanoeWang/rime-lua-aux-code#15]
首先谢谢作者提供的插件，特别好用，
然后有没有可能加一个patch的方式，实现辅助码的显示和隐藏，现在的显示方式词组没有提示，单字有提示，显得很乱，
一些老用户的话，辅码应该都能掌握的差不多
然后说明文件有个小错误，
![image](https://github.com/HowcanoeWang/rime-lua-aux-code/assets/90947781/d43d45e8-54a7-4c50-a12b-7645704bc49d)
这个分号应该是冒号

**Comment by YummyCocoa** [comment]
试了一下，是 auxCode.lua 里转义问题，把：
```lua
local trigger_pattern = env.trigger_key_string:gsub("%W", "%%%1") -- 處理特殊字符
```
替换为 ：
```lua
local trigger_pattern =  env.trigger_key_string
```
就可以了。 估计是之前 @Mintimate 写了 `alt_lua_punc` 方法修复上部分 bug 后，后面这些漏了。
