### ISSUE TITLE
可以设置成直接辅助码吗？

### ISSUE THREAD

**Issue by ysysqd** [HowcanoeWang/rime-lua-aux-code#20]
像手心那样，只要一位辅助码，不用符号引导，输入两码后第三码是辅助码，四码后第五码是辅助码

**Comment by HowcanoeWang** [comment]
这种情况适合单字码表作为词典，不适用我们的筛选方案

> * 此方案适用于使用辅助码排序候选项，而非音形结合的**四键单字**输入模式 （请用单字字库来满足需求）
