### ISSUE TITLE
Windows 小狼毫根据教程挂接之后发现没有办法正常使用

### ISSUE THREAD

**Issue by expoli** [HowcanoeWang/rime-lua-aux-code#5]
1. 尝试过打开插件的 log 部分,但是找不到具体的日志文件
2. 查看小狼毫的日志文件,发现并没有加载 aux_code 的 lua 日志

- 运行环境：win11
- 小狼毫最新版本（0.15.00）
- 原始方案：雾凇
- 输入状态展示
![图片](https://github.com/HowcanoeWang/rime-lua-aux-code/assets/31023767/901e2f5e-e44d-489d-b605-1e1f6e24664d)
- 配置状态：
![图片](https://github.com/HowcanoeWang/rime-lua-aux-code/assets/31023767/0967a2c1-49bd-43f8-ba18-f59ac49068f9)

**Comment by HowcanoeWang** [comment]
参考这版readme，直接修改schema.yaml而不是cumtom.yaml试试？
https://github.com/HowcanoeWang/rime-lua-aux-code/blob/4ad1705d54d21a5a6967ccbfc97c5c0a3aa8e8da/README.md

**Comment by AiraNadih** [comment]
我和你的系统环境完全一样，也是 Win 11 和最新版的小狼毫，而且也是基于雾凇的配置。

建议你查看一下 build 目录中生成的小鹤输入法的 schema.yaml 文件，检查一下该文件中的相关配置是否已经正确修改并生效。

**Comment by AiraNadih** [comment]
顺便提一下，我还在 Android 设备上使用了同文输入法来测试这个 lua 插件，同样基于雾凇配置。不过遇到了个小问题，同文输入法似乎没能正确解析 `filters+` 这种格式，因此我只能先复制原有的 `filters` 设置，再进行手动添加。

最后配置完成的效果如下图所示：
![IMG_20231128_154407](https://github.com/HowcanoeWang/rime-lua-aux-code/assets/128119996/599e60c3-75d7-40d7-bc56-377094e304c1)

但对于 Windows 平台上的小狼毫，尤其是最新版本，理应不存在这种解析问题。我自己也在用，确实没遇到过类似的问题。

**Comment by AiraNadih** [comment]
对了，你有没有下载那个 `flypy_full.txt` 文件？这个文件也需要放置在 lua 目录下，否则这个配置是不会生效的。

**Comment by expoli** [comment]
> 参考这版readme，直接修改schema.yaml而不是cumtom.yaml试试？ https://github.com/HowcanoeWang/rime-lua-aux-code/blob/4ad1705d54d21a5a6967ccbfc97c5c0a3aa8e8da/README.md

使用这种方式可以了，现在没什么问题了

**Comment by expoli** [comment]
https://github.com/expoli/rime-ice

这是我现在的配置

**Comment by expoli** [comment]
> > 参考这版readme，直接修改schema.yaml而不是cumtom.yaml试试？ https://github.com/HowcanoeWang/rime-lua-aux-code/blob/4ad1705d54d21a5a6967ccbfc97c5c0a3aa8e8da/README.md
> 
> 使用这种方式可以了，现在没什么问题了

好奇这个是什么问题，版本不兼容的问题吗？

**Comment by AiraNadih** [comment]
> https://github.com/expoli/rime-ice
> 
> 这是我现在的配置

老实说，我更倾向于采用 custom.yaml 这种配置方式，这样在后期同步更新雾凇的配置时会更加便捷，免去了处理冲突的麻烦。你可以直接复制现有的 `filters` 设置，然后根据需要进行手动添加。

根据我之前在 Win 11 上的测试经验，使用 custom.yaml 配合 `filters+` 的配置方法应该是行得通的。

**Comment by expoli** [comment]
> > https://github.com/expoli/rime-ice
> > 这是我现在的配置
> 
> 老实说，我更倾向于采用 custom.yaml 这种配置方式，这样在后期同步更新雾凇的配置时会更加便捷，免去了处理冲突的麻烦。你可以直接复制现有的 `filters` 设置，然后根据需要进行手动添加。
> 
> 根据我之前在 Win 11 上的测试经验，使用 custom.yaml 配合 `filters+` 的配置方法应该是行得通的。

嗯、是的，但是不清楚为什么 custom 配置为什么不生效 😅我再尝试一下

**Comment by expoli** [comment]
![图片](https://github.com/HowcanoeWang/rime-lua-aux-code/assets/31023767/4b0ebe99-b28b-4bac-a838-017ca5b0928d)
上面是 build 之后的文件，难道是这个双引号的问题？

custom 配置文件
![图片](https://github.com/HowcanoeWang/rime-lua-aux-code/assets/31023767/60a8e830-a225-4255-a872-02b4c02212ed)

**Comment by expoli** [comment]
手动删除成这样就可以了（能理解，但是不知道具体应该怎么做能达到这个效果

![图片](https://github.com/HowcanoeWang/rime-lua-aux-code/assets/31023767/d0de0b0e-a7a1-44e4-9f7f-b2099b6d2cc4)

**Comment by expoli** [comment]
看样子是没有解析 filters+ 的问题，这个是小狼毫的问题吗？

**Comment by AiraNadih** [comment]
> 看样子是没有解析 filters+ 的问题，这个是小狼毫的问题吗？

我重新查阅了相关文档，发现问题出在我遗漏了一个 `/` 符号。。。😂
正确的配置应该是 `filters/+` 。
之前我还以为是同文输入法没正确解析。。。😂

**Comment by AiraNadih** [comment]
@HowcanoeWang 请你更新文档后，加上 Android 平台的同文输入法也经过测试的说明。

**Comment by expoli** [comment]
是的，是这个问题，更新之后就没有问题了

**Comment by expoli** [comment]
> @HowcanoeWang 请你更新文档后，加上 Android 平台的同文输入法也经过测试的说明。

顺手提交了一个 pr（混个贡献者 😁
