### ISSUE TITLE
使用 git 进行下载与配置更新

### ISSUE THREAD

**Issue by expoli** [HowcanoeWang/rime-lua-aux-code#8]
现在更新确实是个问题，我在想要不要使用 git 的 submodule ，将这个项目作为 lua 文件夹里面的一个子文件夹，这样每次更新的时候，直接拉取 git 就可以，省去了自己复制替换的问题。

类似于雾凇的这个：
![图片](https://github.com/HowcanoeWang/rime-lua-aux-code/assets/31023767/65a91fc0-2476-4838-adb9-1478abd8446c)

你们觉得怎么样，具体实现方式，我尝试一下

**Comment by expoli** [comment]
已经测试完成。
下面对应的一些操作
1. 首先把原来的文件删除掉 https://github.com/expoli/rime-ice/commit/71d3c80edbf27ba39f2933efc0a0100a70a7b83b
2. 在 `lua` 目录下使用 `git submodule add https://github.com/HowcanoeWang/rime-lua-aux-code.git rime_lua_aux_code` 添加子模块关联。
3. 修改对应的配置文件进行配置
https://github.com/expoli/rime-ice/commit/c398c5343805a08781f1925562ff72da91cd8976
4. 提交所有更改
5. 更新 sub module 的时候，需要执行，拉取 rime-lua-aux-code 更新，重新部署即可
```shell
git submodule init
git submodule update
```

**Comment by expoli** [comment]
当然，如果自己的配置文件不是使用 git 进行管理的，那么完全可以直接将本项目克隆到 lua 文件夹里面，进行同样的配置即可。需要更新的时候，只需要 git pull 即可

**Comment by HowcanoeWang** [comment]
目前版本已经基本趋于稳定，所有的更新都是小修小补，不更新也不会影响使用，个人感觉还是没有必要用上git子模块来进行版本管理和更新，把部署过程复杂化了且增加了配置中的路径长度。

真的需要更新的话，全选复制一下lua文件的源代码粘贴覆盖即可

**Comment by expoli** [comment]
是的，说得没错，只是个人想法吧，因为我个人的配置文件是git托管的，所以个人感觉直接子模块引用，更方便点，一套配置通用。

都可以，看个人喜好

**Comment by HowcanoeWang** [comment]
晚上我来合并一下readme，把git submodules说明部分作为折叠内容放进去吧

**Comment by HowcanoeWang** [comment]
@expoli 你确定 `lua_filter@aux_code` 能起效？你git clone之后的脚本路径不应该是 `/lua/rime_lua_aux_code/lua/aux_code.lua` 吗？所以配置应该变成 `- lua_filter@rime_lua_aux_code/lua/aux_code@rime_lua_aux_code/lua/flypy_full` 才对？

```markdown
-- RIME 输入法辅助码与音形分离插件
-- engine/filters/+ 增加 - lua_filter@aux_code@rime_lua_aux_code/lua/flypy_full
-- 第二个 @ 后面的是辅助码文件路径，可以自定义
aux_code = require("rime_lua_aux_code.lua.aux_code")
```

你看看这个离谱的路径长度 😸️

**Comment by expoli** [comment]
> @expoli 你确定 `lua_filter@aux_code` 能起效？你git clone之后的脚本路径不应该是 `/lua/rime_lua_aux_code/lua/aux_code.lua` 吗？所以配置应该变成 `- lua_filter@rime_lua_aux_code/lua/aux_code@rime_lua_aux_code/lua/flypy_full` 才对？
> 
> ```markdown
> -- RIME 输入法辅助码与音形分离插件
> -- engine/filters/+ 增加 - lua_filter@aux_code@rime_lua_aux_code/lua/flypy_full
> -- 第二个 @ 后面的是辅助码文件路径，可以自定义
> aux_code = require("rime_lua_aux_code.lua.aux_code")
> ```
> 
> 你看看这个离谱的路径长度 😸️

哈哈，是的，所以我是在 rime.lua 中进行了引入，那么这样的话，就不会有那么长的路径了，上面有提到

**Comment by expoli** [comment]
> > @expoli 你确定 `lua_filter@aux_code` 能起效？你git clone之后的脚本路径不应该是 `/lua/rime_lua_aux_code/lua/aux_code.lua` 吗？所以配置应该变成 `- lua_filter@rime_lua_aux_code/lua/aux_code@rime_lua_aux_code/lua/flypy_full` 才对？
> > 
> > ```markdown
> > -- RIME 输入法辅助码与音形分离插件
> > -- engine/filters/+ 增加 - lua_filter@aux_code@rime_lua_aux_code/lua/flypy_full
> > -- 第二个 @ 后面的是辅助码文件路径，可以自定义
> > aux_code = require("rime_lua_aux_code.lua.aux_code")
> > ```
> > 
> > 你看看这个离谱的路径长度 😸️
> 
> 哈哈，是的，所以我是在 rime.lua 中进行了引入，那么这样的话，就不会有那么长的路径了，上面有提到

还有后面加那么多的路径是因为，我看到代码在查找对应的字典文件时，是直接基于 rime 用户文件加生成的绝对路径，如果支持直接在 aux 自己的当前目录中进行字典寻址的话（即：在 aux_code.lua 目录下进行字典查找，就不需要那么长的路径了）

**Comment by HowcanoeWang** [comment]
> 哈哈，是的，所以我是在 rime.lua 中进行了引入，那么这样的话，就不会有那么长的路径了，上面有提到

奥卡姆剃刀：如无必要，勿增实体

又是git clone，后面还得git pull敲一大堆指令，还修改了lua引入代码，一通操作猛如虎，感觉还是不如直接复制粘贴源码 😄️

**Comment by HowcanoeWang** [comment]
最后决定还是移除 git 安装说明，有需要的可以参考这个issue

---

1. 首先进入到 rime 用户文件夹的 lua 目录下面

(此步骤有两种方式，适合两种用户，请根据自己的需要进行选择）

2. 开始安装
  - 直接 git clone 的方式
    - 执行 `git clone`` 命令，将此项目克隆到 lua 目录下（下面是将此项目 clone 为 rime_lua_aux_code 文件夹）

      ```shell
      git clone https://github.com/HowcanoeWang/rime-lua-aux-code rime_lua_aux_code
      ```
  - `git submodule` 方式
    > 注意⚠️：此种方式只适合你的 rime 配置文件也是使用 git 进行托管的场景
    - 执行 `git submodule` 命令
      ```shell
      git submodule add https://github.com/HowcanoeWang/rime-lua-aux-code rime_lua_aux_code
      ```
3. 修改 `rime.lua` 添加 aux_code
  aux_code = require("rime_lua_aux_code.lua.aux_code")
  ```yaml
  -- RIME 输入法辅助码与音形分离插件
  -- engine/filters/+ 增加 - lua_filter@aux_code@rime_lua_aux_code/lua/flypy_full
  -- 第二个 @ 后面的是辅助码文件路径，可以自定义
  ```

**Comment by expoli** [comment]
我觉得现在这个处理不错👍，解决方法确实有点绕了。😄不过也是提供了一个思路。
